//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyViews.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyViews.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackMessage {
            get {
                object obj = ResourceManager.GetObject("BackMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackMessage1 {
            get {
                object obj = ResourceManager.GetObject("BackMessage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackMessage2 {
            get {
                object obj = ResourceManager.GetObject("BackMessage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueGate {
            get {
                object obj = ResourceManager.GetObject("BlueGate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PTG
        ///GTG
        ///GTE.
        /// </summary>
        internal static string EnemyMoveTestMap1 {
            get {
                return ResourceManager.GetString("EnemyMoveTestMap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fire {
            get {
                object obj = ResourceManager.GetObject("fire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fist {
            get {
                object obj = ResourceManager.GetObject("fist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fist1 {
            get {
                object obj = ResourceManager.GetObject("fist1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ghost {
            get {
                object obj = ResourceManager.GetObject("ghost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ghosts {
            get {
                object obj = ResourceManager.GetObject("ghosts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenGate {
            get {
                object obj = ResourceManager.GetObject("GreenGate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heal {
            get {
                object obj = ResourceManager.GetObject("heal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_blue {
            get {
                object obj = ResourceManager.GetObject("key_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_green {
            get {
                object obj = ResourceManager.GetObject("key_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_red {
            get {
                object obj = ResourceManager.GetObject("key_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Land {
            get {
                object obj = ResourceManager.GetObject("Land", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFFFFFPFFFFFFF
        ///FFFFGGTGGFFFFF
        ///FFFFGGTGFFFFFF
        ///FFFFGGTTTFFFFF
        ///FFFFGTTF1FFFFF
        ///FFFFGXFFOFFFFF
        ///FFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFF.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFFFFFPFFFFFFF
        ///FFFWWGTTTTTTTH
        ///FFFWGGTGGGGGGF
        ///FFGGGGTGGGGGGG
        ///FFGTTTTTGGGGGG
        ///FFETTTTTTTTTT&lt;
        ///FFTTTGGGGWWWWW
        ///FFTTGGGGWWWWWW
        ///FFTGGGGGWWWWWW
        ///FFTGGGGGWWWWWW
        ///FFTFGGGGWWWWWW
        ///FTTFGGGGWWWWWW
        ///FTFGGGGGWWWWWW
        ///F\FGGGGWWWWWWW
        ///FXFGWWWWWWWWWW.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FPFFEFFFFFFFFFF
        ///FTFGTGGGGGGGEFF
        ///FTTTTTGGGGGGTFF
        ///FGTTTTTTTTTTT@F
        ///FGTTGGGGGGWWWWF
        ///FGTGGGT2GWWWWWF
        ///FGTTTTTOGGWWWWF
        ///FGTTGGTHGWWWWWF
        ///FFTGGGGGWWWWWWF
        ///FFTGGGGGGFFFFFF
        ///FFTTGGGGFFFFFFF
        ///FFFTGGGGGFFFFFF
        ///FFFTGGGGGFFFFFF
        ///FFFTGGGGGFFFFFF
        ///FFFXGGGGGFFFFFF.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFFPFFWWWWWWWWW
        ///FFFTFFFWWWWWWWW
        ///FFGTFTTTWWWWWWW
        ///FGTTTTFTTETFFFW
        ///GTTGGGFFFFTET&gt;F
        ///GTGGGGFFFFFFFFF
        ///GTTTTTTTTTTGGGG
        ///GGGGGGGGGGEGG!G
        ///GGGGGGGGTTTGGFF
        ///GGGTTTTTTGGGGGG
        ///FFFTFFFTTGGGGGG
        ///FFFTFFFTFGGGGGG
        ///FFFTFFF|FGGGGGG
        ///#T/TFFFTFGGGGGG
        ///FFFFFFFTFGGGGGG
        ///WWWWFFFXFGGGGGG
        ///.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFFXT3FFWWWWWWW
        ///FFF\FOFWWWWWWWW
        ///FFF|FFWWWWWWWWW
        ///FFF/GFFFFWWWWWW
        ///FFGTTTTTTETTTT&lt;
        ///FGGTTGGGGGGGGGG
        ///GGTTGGGGGEGGWWW
        ///PTTTTTTGGGGGGWW
        ///GGTGGGGGGGFFFFF
        ///GGTGGGGGGFFFFFF
        ///GGTTTTTTTEEE!HH
        ///&gt;TETGGGGGFFFFFF
        ///FGGGGGGGGGGGGGF
        ///FFFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFFF
        ///FFFFFFFFFFFFFFF
        ///.
        /// </summary>
        internal static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GP
        ///G&lt;.
        /// </summary>
        internal static string MapForTest2x2 {
            get {
                return ResourceManager.GetString("MapForTest2x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MyGrass {
            get {
                object obj = ResourceManager.GetObject("MyGrass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MyTrail {
            get {
                object obj = ResourceManager.GetObject("MyTrail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newGrass {
            get {
                object obj = ResourceManager.GetObject("newGrass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newGrass1 {
            get {
                object obj = ResourceManager.GetObject("newGrass1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newHealer {
            get {
                object obj = ResourceManager.GetObject("newHealer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newLand {
            get {
                object obj = ResourceManager.GetObject("newLand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newLand1 {
            get {
                object obj = ResourceManager.GetObject("newLand1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newTrail {
            get {
                object obj = ResourceManager.GetObject("newTrail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newTrail1 {
            get {
                object obj = ResourceManager.GetObject("newTrail1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newWater {
            get {
                object obj = ResourceManager.GetObject("newWater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newWater1 {
            get {
                object obj = ResourceManager.GetObject("newWater1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap npc {
            get {
                object obj = ResourceManager.GetObject("npc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player {
            get {
                object obj = ResourceManager.GetObject("player", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player1 {
            get {
                object obj = ResourceManager.GetObject("player1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порой, тяга к деньгам может все испорить. В погоне за хорошей работой человек может потерять все. Именно так и произошло с нашим персонажем..
        /// </summary>
        internal static string Prologue1 {
            get {
                return ResourceManager.GetString("Prologue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наш герой стремился к богатству. Он жертвовал практически всем, ради денег. Он считал, что они его сделают счастливым. Однако он ошибался..
        /// </summary>
        internal static string Prologue2 {
            get {
                return ResourceManager.GetString("Prologue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Однажды он заметил, что у него никого нет. Нет друзей, нет близого человека, да и родители находятся очень далеко и контакт с ними давно не поддерживался..
        /// </summary>
        internal static string Prologue3 {
            get {
                return ResourceManager.GetString("Prologue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на И однажды, идя по какому то старому рынку, он находит очень странного человека, который предлагает ему купить книгу, говоря, что в ней есть то, что нужно нашему персонажу..
        /// </summary>
        internal static string Prologue4 {
            get {
                return ResourceManager.GetString("Prologue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наш герой не долго думаю решается купить эту книгу. Придя домой он начинает рассматривать покупку: нет обложки, старые потрепанные страницы пахнут сыростью и пылью..
        /// </summary>
        internal static string Prologue5 {
            get {
                return ResourceManager.GetString("Prologue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изучив ее, наш герой осознает, что где то очень далеко, где никого нет, где страшно и одиноко, находится то, что может изменить его жизнь..
        /// </summary>
        internal static string Prologue6 {
            get {
                return ResourceManager.GetString("Prologue6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотрев на свою жизнь, герой решает бросить все и отправиться искать &quot;То, не знаю что&quot;, в надежде изменить свою жизнь и обрести простое человеческое счастье..
        /// </summary>
        internal static string Prologue7 {
            get {
                return ResourceManager.GetString("Prologue7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Потратив около недели на сборы, покупку билетов, дорогу, наш персонаж прибывает на место, указанное в книге. Именно отсюда должен начаться его длинный путь....
        /// </summary>
        internal static string Prologue8 {
            get {
                return ResourceManager.GetString("Prologue8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дойдя до первого места, отмеченного в книге, наш герой видит загадочного старца, желающего рассказать ему что то важное....
        /// </summary>
        internal static string Prologue9 {
            get {
                return ResourceManager.GetString("Prologue9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedGate {
            get {
                object obj = ResourceManager.GetObject("RedGate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rock {
            get {
                object obj = ResourceManager.GetObject("Rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap soldier {
            get {
                object obj = ResourceManager.GetObject("soldier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sword {
            get {
                object obj = ResourceManager.GetObject("sword", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap swordWood {
            get {
                object obj = ResourceManager.GetObject("swordWood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WWWFFTFFFFWWWW
        ///WWWGGTGGGFWWWW
        ///WWGGPTGTGFWWWW
        ///FGGGTG1TGFWWWW
        ///FG&lt;TTHOTGFWWWW
        ///FG!TTGGGGGWWGG
        ///FG&gt;TTGGGGGGGGG
        ///FGT\|/TTTTTTEX
        ///FGTGGGGGGGGWGG
        ///GTTGGGGGGGGGGG
        ///GGTGGGWWWWGGLL
        ///GGTTGGWWWWGGGL
        ///G@TTTWWWWWGGGG
        ///G#TTTWWWWWGGGG.
        /// </summary>
        internal static string TestMap {
            get {
                return ResourceManager.GetString("TestMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTPTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGG [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TestMap_2 {
            get {
                return ResourceManager.GetString("TestMap_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WWWFFTFFFFWWWWGGGGGGGGGGGGGGG
        ///WWWGGTGGGFWWWWGGGGGGGGGGGGGGG
        ///WWGGTTGTGFWWWWGGGGGGGGGGGGGGG
        ///FGGGTGGTGFWWWWGGGGGGGGGGGGGGG
        ///FGGTTTTTGFWWWWGGGGGGGGGGGGGGG
        ///FGGTTGGGGGWWGGGGGGGGGGGGGGGGG
        ///FGGTTGGGGGGGGGGGGGGGGGGGGGGGG
        ///FGTTTTTTTTTTTETTTTTTTTTTTTTTT
        ///FGTTTTTTTTTTTTTTTTTTTTTTTTTTT
        ///GTTGGGGGGGGGGGGGGGGTTGGGGGGGG
        ///GGTGGGWWWWGGLLGGGGGTTGGGGGGGG
        ///GGTTGGWWWWGGGLGGGGGTTGEGGGGGG
        ///GTTTTWWWWWGGGGGGGGGTTGGGGGGGG
        ///GTTTTWWWWWGGGGGGGGGTTGGGGGGGG
        ///WWWFFTFFFFWWWWGGGGGTTGGGGGGGG
        ///WWWGGTGGGFWWWWGGGGGTTGGGGGGGG
        ///WWGGTHGTGFWWWWGG [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TestMap3 {
            get {
                return ResourceManager.GetString("TestMap3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap testPlayer {
            get {
                object obj = ResourceManager.GetObject("testPlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestPng2 {
            get {
                object obj = ResourceManager.GetObject("TestPng2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestPng3 {
            get {
                object obj = ResourceManager.GetObject("TestPng3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFFFFFFFFPFFFFFFFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTTNGGGGFFFFFF
        ///FFFGGGGGGTGOGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGGGTGGGGGGFFFFFF
        ///FFFGGGGG [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TestSizeMap_20x20 {
            get {
                return ResourceManager.GetString("TestSizeMap~20x20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СПРАВКА:
        ///Чтобы передвигаться, используйте w / a / s / d
        ///Чтобы поговорить со старцем, подойдите к нему и нажмите T (на английской раскладке).
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tree {
            get {
                object obj = ResourceManager.GetObject("Tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tree1 {
            get {
                object obj = ResourceManager.GetObject("Tree1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up0 {
            get {
                object obj = ResourceManager.GetObject("up0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up1 {
            get {
                object obj = ResourceManager.GetObject("up1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up2 {
            get {
                object obj = ResourceManager.GetObject("up2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up3 {
            get {
                object obj = ResourceManager.GetObject("up3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up4 {
            get {
                object obj = ResourceManager.GetObject("up4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up5 {
            get {
                object obj = ResourceManager.GetObject("up5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up6 {
            get {
                object obj = ResourceManager.GetObject("up6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up7 {
            get {
                object obj = ResourceManager.GetObject("up7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up8 {
            get {
                object obj = ResourceManager.GetObject("up8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Water {
            get {
                object obj = ResourceManager.GetObject("Water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
