//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyViews.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyViews.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PTG
        ///GTG
        ///GTE.
        /// </summary>
        internal static string EnemyMoveTestMap1 {
            get {
                return ResourceManager.GetString("EnemyMoveTestMap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ghost {
            get {
                object obj = ResourceManager.GetObject("ghost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heal {
            get {
                object obj = ResourceManager.GetObject("heal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Land {
            get {
                object obj = ResourceManager.GetObject("Land", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MyGrass {
            get {
                object obj = ResourceManager.GetObject("MyGrass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MyTrail {
            get {
                object obj = ResourceManager.GetObject("MyTrail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newGrass {
            get {
                object obj = ResourceManager.GetObject("newGrass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newGrass1 {
            get {
                object obj = ResourceManager.GetObject("newGrass1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newHealer {
            get {
                object obj = ResourceManager.GetObject("newHealer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newLand {
            get {
                object obj = ResourceManager.GetObject("newLand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newLand1 {
            get {
                object obj = ResourceManager.GetObject("newLand1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newTrail {
            get {
                object obj = ResourceManager.GetObject("newTrail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newTrail1 {
            get {
                object obj = ResourceManager.GetObject("newTrail1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newWater {
            get {
                object obj = ResourceManager.GetObject("newWater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newWater1 {
            get {
                object obj = ResourceManager.GetObject("newWater1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player {
            get {
                object obj = ResourceManager.GetObject("player", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player1 {
            get {
                object obj = ResourceManager.GetObject("player1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rock {
            get {
                object obj = ResourceManager.GetObject("Rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WWWFFTFFFFWWWW
        ///WWWGGTGGGFWWWW
        ///WWGGPTGTGFWWWW
        ///FGGGTGGTGFWWWW
        ///FGGTTHTTGFWWWW
        ///FGGTTGGGGGWWGG
        ///FGGTTGGGGGGGGG
        ///FGTTTTTTTTTTEX
        ///FGTGGGGGGGGWGG
        ///GTTGGGGGGGGGGG
        ///GGTGGGWWWWGGLL
        ///GGTTGGWWWWGGGL
        ///GTTTTWWWWWGGGG
        ///GTTTTWWWWWGGGG.
        /// </summary>
        internal static string TestMap {
            get {
                return ResourceManager.GetString("TestMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTPTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGG [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TestMap_2 {
            get {
                return ResourceManager.GetString("TestMap_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WWWFFTFFFFWWWWGGGGGGGGGGGGGGG
        ///WWWGGTGGGFWWWWGGGGGGGGGGGGGGG
        ///WWGGTTGTGFWWWWGGGGGGGGGGGGGGG
        ///FGGGTGGTGFWWWWGGGGGGGGGGGGGGG
        ///FGGTTTTTGFWWWWGGGGGGGGGGGGGGG
        ///FGGTTGGGGGWWGGGGGGGGGGGGGGGGG
        ///FGGTTGGGGGGGGGGGGGGGGGGGGGGGG
        ///FGTTTTTTTTTTTETTTTTTTTTTTTTTT
        ///FGTTTTTTTTTTTTTTTTTTTTTTTTTTT
        ///GTTGGGGGGGGGGGGGGGGTTGGGGGGGG
        ///GGTGGGWWWWGGLLGGGGGTTGGGGGGGG
        ///GGTTGGWWWWGGGLGGGGGTTGEGGGGGG
        ///GTTTTWWWWWGGGGGGGGGTTGGGGGGGG
        ///GTTTTWWWWWGGGGGGGGGTTGGGGGGGG
        ///WWWFFTFFFFWWWWGGGGGTTGGGGGGGG
        ///WWWGGTGGGFWWWWGGGGGTTGGGGGGGG
        ///WWGGTHGTGFWWWWGG [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TestMap3 {
            get {
                return ResourceManager.GetString("TestMap3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap testPlayer {
            get {
                object obj = ResourceManager.GetObject("testPlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestPng2 {
            get {
                object obj = ResourceManager.GetObject("TestPng2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestPng3 {
            get {
                object obj = ResourceManager.GetObject("TestPng3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tree {
            get {
                object obj = ResourceManager.GetObject("Tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tree1 {
            get {
                object obj = ResourceManager.GetObject("Tree1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Water {
            get {
                object obj = ResourceManager.GetObject("Water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
