//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGameModel.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGameModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string FirstMapTest {
            get {
                return ResourceManager.GetString("FirstMapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .bmp.
        /// </summary>
        internal static string Grass {
            get {
                return ResourceManager.GetString("Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Land {
            get {
                object obj = ResourceManager.GetObject("Land", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MyGrass {
            get {
                object obj = ResourceManager.GetObject("MyGrass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MyTrail {
            get {
                object obj = ResourceManager.GetObject("MyTrail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rock {
            get {
                object obj = ResourceManager.GetObject("Rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WWWRRTRRRRWWWW
        ///WWWGGTGGGRWWWW
        ///WWGGPTGTGRWWWW
        ///RGGGTGGTGRWWWW
        ///RGGTTTTTGRWWWW
        ///RGGTTGGGGGWWGG
        ///RGGTTGGGGGGGGG
        ///RGTTTTTTTTTTTE
        ///RGTGGGGGGGGWGG
        ///GTTGGGGGGGGGGG
        ///GGTGGGWWWWGGLL
        ///GGTTGGWWWWGGGL
        ///GTTTTWWWWWGGGG
        ///GTTTTWWWWWGGGG.
        /// </summary>
        internal static string TestMap {
            get {
                return ResourceManager.GetString("TestMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTPTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGGGGGGGGTTTTTTTTTTGGGGGGGGGGGGGGGG
        ///GGGGGGGG [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TestMap_2 {
            get {
                return ResourceManager.GetString("TestMap_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WWWRRTRRRRWWWW
        ///WWWGGTGGGRWWWW
        ///WWGGPTGTGRWWWW
        ///RGGGTGGTGRWWWW
        ///RGGTTTTTGRWWWW
        ///RGGTTGGGGGWWGG
        ///RGGTTGGGGGGGGG
        ///RGTTTTTTTTTTTE
        ///RGTGGGGGGGGWGG
        ///GTTGGGGGGGGGGG
        ///GGTGGGWWWWGGLL
        ///GGTTGGWWWWGGGL
        ///GTTTTWWWWWGGGG
        ///GTTTTWWWWWGGGG
        ///.
        /// </summary>
        internal static string TestMap3 {
            get {
                return ResourceManager.GetString("TestMap3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap testPlayer {
            get {
                object obj = ResourceManager.GetObject("testPlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestPng2 {
            get {
                object obj = ResourceManager.GetObject("TestPng2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestPng3 {
            get {
                object obj = ResourceManager.GetObject("TestPng3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Water {
            get {
                object obj = ResourceManager.GetObject("Water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
